version: '3'

services:
  postgres:
    container_name: pg
    image: postgres:10.0-alpine
    networks:
      - network
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pg_data

  adminer:
    image: adminer
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_DB_NAME: chatty
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    networks:
      - network
    ports:
      - 8080:8080

networks:
  network:
    driver: bridge

volumes:
  data:
